---
title: "test ccnv"
output: html_document
date: "2024-05-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read data and check data}
#for Mac
target_files <- read.csv("/Volumes/PhD/Ependymoma/Ependymoma_methylation_mainCohort/sample_info_02_08_2022_850_Mac.csv", header=TRUE, sep=";")

#
g_files <- paste0(target_files$Basename, "_Grn.idat")
r_files <- paste0(target_files$Basename,"_Red.idat" )

# test if every file is an idat file
test_grn <- sapply(g_files, readChar, nchars = 4)
test_red <- sapply(r_files, readChar, nchars = 4)

#This will give out file names if they are not IDAT and character 0 if all files are IDAT
test_grn[test_grn != "IDAT"]
test_red[test_red != "IDAT"]

#remove duplicates
while (anyDuplicated(target_files$Basename) != "0") {
  target_files <- target_files[-anyDuplicated(target_files$Basename),]
}

PFB2_5 <- target_files[which(target_files$Classifier_new_version_condensed == "EPN_PFB_1_to_5"),]
PFB2_5 <- PFB2_5[-which(PFB2_5$Classifier_new_version == "EPN_PFB_1"),]

cumul.CNV(PFB2_5, segmentationMode = "multi")

#details <- read.csv("/Volumes/PhD/Ependymoma/Ependymoma_methylation_mainCohort/detail_conumee.csv")
#detail_regions <- details$name

```

```{r testing mouse}
#for Mac
target_files <- read.csv("/Volumes/PhD/Maus_idats_Melanie/IDH_H3WT_hGFAP_cre_P53_Lin28A_Primarytumor/MausIdats1.csv", header=TRUE, sep=";")

#
g_files <- paste0(target_files$Basename, "_Grn.idat")
r_files <- paste0(target_files$Basename,"_Red.idat" )

# test if every file is an idat file
test_grn <- sapply(g_files, readChar, nchars = 4)
test_red <- sapply(r_files, readChar, nchars = 4)

#This will give out file names if they are not IDAT and character 0 if all files are IDAT
test_grn[test_grn != "IDAT"]
test_red[test_red != "IDAT"]

#remove duplicates
while (anyDuplicated(target_files$Basename) != "0") {
  target_files <- target_files[-anyDuplicated(target_files$Basename),]
  
}

"/Volumes/PhD/Maus_idats_Melanie/IDH_H3WT_hGFAP_cre_P53_Lin28A_Primarytumor/205537640001_R02C01"

prepCNVImport <-  function(target_files, Array_Type) {
  targetDirectory <- dirname(target_files$Basename[1])
  sample_sheet <- data.frame(matrix(0, 3 , length(target_files$Basename)))
  names(sample_sheet) <- c("Sample_Name", "Sentrix_ID", "Sentrix_Position")
  for (i in 1:length(target_files$Basename)) {
    sample_sheet$Sample_Name[i] <- basename(target_files$Basename[i])
    Sentrix_parts <- strsplit(sample_sheet$Sample_Name[i], "_")[[1]]
    sample_sheet$Sentrix_ID[i] <- filename_parts[1]
    sample_sheet$Sentrix_Position[i] <- filename_parts[2]
  }
  return(list("array_type" = Array_Type, "directory" = targetDirectory, "sample_sheet" = sample_sheet))
}

forCNVImp <- prepCNVImport(target_files, "mouse")


cumul.CNV(PFB2_5, segmentationMode = "multi")

```

