---
title: "Untitled"
author: "Antonia Gocke"
date: "2024-02-06"
output: pdf_document
---

```{r package loading}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(minfi))
suppressPackageStartupMessages(library(minfiData))
suppressPackageStartupMessages(library(minfiDataEPIC))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(IlluminaHumanMethylation450kanno.ilmn12.hg19))
suppressPackageStartupMessages(library(IlluminaHumanMethylationEPICanno.ilm10b4.hg19))
suppressPackageStartupMessages(library(conumee))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(foreach))
library(GenVisR)
```

```{r Parameters to give function}
#ArrayType <- kann 450k, EPIC oder overlap sein
# threshhold <- default 0.2
options(rstudio.help.showDataPreview = FALSE)
options(scipen = 999)
```


```{r read data and check data}
target_files <- read.csv("D:/Ependymoma/Ependymoma_methylation_mainCohort/sample_info_02_08_2022_850.csv", header=TRUE, sep=";")

#
g_files <- paste0(target_files$Basename, "_Grn.idat")
r_files <- paste0(target_files$Basename,"_Red.idat" )

# test if every file is an idat file
test_grn <- sapply(g_files, readChar, nchars = 4)
test_red <- sapply(r_files, readChar, nchars = 4)

#This will give out file names if they are not IDAT and character 0 if all files are IDAT
test_grn[test_grn != "IDAT"]
test_red[test_red != "IDAT"]

#remove duplicates
while (anyDuplicated(target_files$Basename) != "0") {
  target_files <- target_files[-anyDuplicated(target_files$Basename),]
}

target_files <- target_files[which(target_files$Classifier_new_version_condensed == "EPN_SPINE_MYCN"),]
detail_regions <- read.csv("D:/Ependymoma/Ependymoma_methylation_mainCohort/detail_conumee.csv")

```

```{r}

updatempcf <- function(data, gamma=5){

  #Check data input:
  chrom <- data[,1]
  position <- data[,2]
  nSample <- ncol(data)-2
  sampleid <- colnames(data)[-c(1:2)]
  nSample <- length(sampleid)

	#Initialize
  seg.names <- c("chrom","start.pos","end.pos","n.probes",sampleid)
  mpcf.names <- c("chrom","pos",sampleid)
  segments <- data.frame(matrix(nrow=0,ncol=nSample+5))
	colnames(segments) <- seg.names

  #Scale gamma according to the number of samples:
  gamma <- gamma*nSample
  num.chrom <- chrom
  chrom.list <- unique(num.chrom)
  nChrom <- length(chrom.list)

	#run multiPCF separately on each chromosome:
  for(c in 1:nChrom){
    
    probe.c <- which(num.chrom==chrom.list[c])
    pos.c <- position[probe.c]
    nProbe.c <- length(probe.c)
    
    #get data for this chrom
		chrom.data <- data[which(data$Chrom == c),]
		chrom.data <- chrom.data[,-c(1:2)]

    #Run multipcf:
    mpcf <- runFastMultiPCF(as.matrix(chrom.data),gamma=gamma, 0.15, 0.15)    #requires samples in columns, probes in rows

    #Information about segments:
    nSeg <- mpcf$nIntervals
		start0 <- mpcf$start0
		n.pos <- mpcf$length
		seg.mean <- t(mpcf$mean)  #get samples in columns
		posStart <- pos.c[start0]
		posEnd <- c(pos.c[start0-1],pos.c[nProbe.c])

    #Chromosome number and character arm id:
    chr <- unique(chrom[probe.c])
		chrid <- rep(chr,times=nSeg)

		#Round
		seg.mean <- round(seg.mean,digits=4)

    #Data frame:
		segments.c <- data.frame(chrid,posStart,posEnd,n.pos,seg.mean,stringsAsFactors=FALSE)
		colnames(segments.c) <- seg.names

    #Append results for this arm:
    segments <- rbind(segments,segments.c)

   }
  #return results:
  return(segments)
}


# Fast version 
runFastMultiPCF <- function (x, gamma, frac1, frac2) {
  mark <- rep(0, nrow(x))
	mark<-sawMarkM(x,frac1,frac2)
	dense <- compactMulti(t(x), mark)
	compPotts <- multiPCFcompact(dense$Nr, dense$Sum, gamma)
		return(list(length = compPotts$Lengde, start0 = compPotts$sta,
        		mean = compPotts$mean, nIntervals = compPotts$nIntervals))
}

## sawtooth-filter for multiPCF - marks potential breakpoints. Uses two
## sawtoothfilters, one lang (length L) and one short (fixed length 6)
sawMarkM <- function(x, frac1, frac2){
  L = 15
 nrProbes <- nrow(x)
  nrSample <- ncol(x)
  mark <- rep(0, nrProbes)
  sawValue <- rep(0, nrProbes)
  filter <- rep(0, 2 * L)
  sawValue2 <- rep(0, nrProbes)
  filter2 <- rep(0, 6)
  for (k in 1:L) {
    filter[k] <- k / L
    filter[2 * L + 1 - k] <- -k / L
  }

  for (k in 1:3) {
    filter2[k] <- k / 3
    filter2[7 - k] <- -k / 3
  }

  for (l in 1:(nrProbes - 2 * L + 1)) {
    for (m in 1:nrSample) {
      diff <- crossprod(filter, x[l:(l + 2 * L - 1), m])
      sawValue[l + L - 1] <- sawValue[l + L - 1] + abs(diff)
    }
  }
  limit <- quantile(sawValue, (1 - frac1))
  for (l in 1:(nrProbes - 2 * L)) {
    if (sawValue[l + L - 1] > limit) {
      mark[l + L - 1] <- 1
    }
  }
  for (l in (L - 1):(nrProbes - L - 2)) {
    for (m in 1:nrSample) {
      diff2 <- crossprod(filter2, x[l:(l + 5), m])
      sawValue2[l + 2] <- sawValue2[l + 2] + abs(diff2)
    }
  }
  limit2 <- quantile(sawValue2, (1 - frac2))
  for (l in (L - 1):(nrProbes - L - 2)) {
    if (sawValue2[l + 2] > limit2) {
      mark[l + 2] <- 1
    }
  }
  for (l in 1:L) {
    mark[l] <- 1
    mark[nrProbes + 1 - l] <- 1
  }

  return(mark)
}

# function that accumulates numbers of observations and sums between potential breakpoints
compactMulti <- function(y, mark) {
 antGen <- ncol(y)
  antSample <- nrow(y)
  antMark <- sum(mark)
  ant <- rep(0, antMark)
  sum <- rep(0, antMark * antSample)
  dim(sum) <- c(antSample, antMark)
  pos <- 1
  oldPos <- 0
  count <- 1
  delSum <- rep(0, antSample)
  while (pos <= antGen) {
    delSum <- 0
    while (mark[pos] < 1) {
      delSum <- delSum + y[, pos]
      pos <- pos + 1
    }
    ant[count] <- pos - oldPos
    sum[, count] <- delSum + y[, pos]
    oldPos <- pos
    pos <- pos + 1
    count <- count + 1
  }
  list(Nr = ant, Sum = sum)
}

multiPCFcompact <- function(nr,sum,gamma) {
  ## nr,sum : numbers and sums for one analysis unit,
  ## typically one chromosomal arm. Samples assumed to be in rows.
  ## gamma: penalty for discontinuities
  N <- length(nr)
	nSamples <- nrow(sum)
	## initialisations
	yhat <- rep(0,N*nSamples);
	dim(yhat) <- c(nSamples,N)
	bestCost <- rep(0,N)
	bestSplit <- rep(0,N+1)
	bestAver <- rep(0,N*nSamples)
	dim(bestAver) <- c(nSamples,N)
	Sum <- rep(0,N*nSamples)
	dim(Sum) <- c(nSamples,N)
	Nevner <- rep(0,N*nSamples)
	dim(Nevner) <- c(nSamples,N)
	eachCost <- rep(0,N*nSamples)
	dim(eachCost) <- c(nSamples,N)
	Cost <- rep(0,N)
	## Filling of first elements
	Sum[ ,1]<-sum[,1]
	Nevner[,1]<-nr[1]
	bestSplit[1]<-0
	bestAver[,1] <- sum[,1]/nr[1]
	helper <- rep(1, nSamples)
	bestCost[1]<-helper%*%(-Sum[,1]*bestAver[,1])
  lengde <- rep(0,N)

	## Solving for gradually longer arrays. Sum accumulates
	## error values for righthand plateau downward from n;
	## this error added to gamma and the stored cost in bestCost
	## give the total cost. Cost stores the total cost for breaks
	## at any position below n, and which.min finds the position
	## with lowest cost (best split). Aver is the average of the
	## righthand plateau.
	for (n in 2:N) {
    Sum[,1:n] <- Sum[ ,1:n]+sum[,n]
		Nevner[,1:n] <- Nevner[,1:n]+nr[n]
		eachCost[,1:n] <- -(Sum[ ,1:n]^2)/Nevner[ ,1:n]
    Cost[1:n] <- helper %*% eachCost[, 1:n]
		Cost[2:n] <- Cost[2:n]+bestCost[1:(n-1)]+gamma
		Pos <- which.min(Cost[1:n])
 		cost <- Cost[Pos]
 		aver <- Sum[ ,Pos]/Nevner[,Pos]
 		bestCost[n] <- cost
 		bestAver[ ,n] <- aver
 		bestSplit[n] <- Pos-1

 	}
	## The final solution is found iteratively from the sequence
	## of split positions stored in bestSplit and the averages
	## for each plateau stored in bestAver
 	n <- N
	antInt <- 0
 	while (n > 0) {
		yhat[ ,(bestSplit[n]+1):n] <- bestAver[ ,n]
 		antInt <- antInt+1
		lengde[antInt] <- sum(nr[(bestSplit[n]+1):n])
		n <- bestSplit[n]
 	}
	lengdeRev <- lengde[antInt:1]
	init <- rep(0,antInt)
	init[1]<-1
	if(antInt>=2){
		for(k in 2:antInt){
			init[k]<-init[k-1]+lengdeRev[k-1]
		}
	}

 	n <- N
	verdi <- rep(0,antInt*nSamples)
	dim(verdi) <- c(nSamples,antInt)
	bestSplit[n+1] <- n
	antall <- antInt
 	while (n > 0) {
 		verdi[ ,antall] <- bestAver[ ,n]
 		n <- bestSplit[n]
		antall <- antall-1
 	}

 	list(Lengde = lengdeRev, sta = init, mean = verdi, nIntervals=antInt)
}
```

```{r}
sampleBinContr <- function(target_rgset, ArrayType) {
  #generate bins
  anno_targets <- conumee::CNV.create_anno(bin_minprobes = 15, bin_minsize = 50000, bin_maxsize = 5000000, array_type = ArrayType)
  # Illumina normalisation
  target_mset <- preprocessIllumina(target_rgset)
  target_mset_mapped <- mapToGenome(target_mset)
  target_mset_loaded <- conumee::CNV.load(target_mset)

  #load controls based on ArrayType
  if (ArrayType == "overlap" || ArrayType == "450k"){
    control_mset <- minifData::MsetEx
  }
  if (ArrayType == "EPIC"){
    control_mset <- minfiDataEPIC::MsetEPIC
  }
  control_mset_loaded <- conumee::CNV.load(control_mset)
  
  # find overlapping probes between arraydata and annotations
  anno_targets@probes <- subsetByOverlaps(anno_targets@probes, granges(target_mset_mapped))
  
  output <- list("target_mset_loaded" = target_mset_loaded, "control_mset_loaded" = control_mset_loaded, "anno_targets" = anno_targets)
  return(output)

}

```


```{r read and segment data}
multiSampleSeg <- function(mSetsAnno, ArrayType, thresh, colour.amplification, colour.loss, detail.regions){
 
  #load and bin each sample in conumee
  foreach(i=1:ncol(mSetsAnno$target_mset_loaded@intensity)) %do%
  {
    if (i == 1) {
      x <- CNV.bin(CNV.fit(query = mSetsAnno$target_mset_loaded[names(mSetsAnno$target_mset_loaded[i])], ref = mSetsAnno$control_mset_loaded, mSetsAnno$anno_targets))
      target_ratios <- cbind(x@anno@bins@ranges@NAMES, x@anno@bins@ranges@start, x@bin$ratio)
    }
   else {
     x <- CNV.bin(CNV.fit(query = mSetsAnno$target_mset_loaded[names(mSetsAnno$target_mset_loaded[i])], ref = mSetsAnno$control_mset_loaded, mSetsAnno$anno_targets))
      target_ratios <- as.data.frame(cbind(target_ratios, x@bin$ratio))
    }
  }
  names(target_ratios) <- c("Chrom", "Median.bp", names(mSetsAnno$target_mset_loaded@intensity))

  target_ratios$Chrom <- gsub("chr","",target_ratios$Chrom)
  target_ratios$Chrom <- substr(target_ratios$Chrom,1,nchar(target_ratios$Chrom)-4)
  target_ratios$Chrom <- sub("\\-", "", target_ratios$Chrom)

  target_ratios <- na.omit(as.data.frame(sapply(target_ratios, as.numeric)))
  
 #################### Segmentation #################################
  seg_mpcf <- updatempcf(target_ratios, gamma = 5)
  
  cumCNV <- CCNV(mSetsAnno, seg_mpcf, target_ratios, colour.amplification, colour.loss, detail.regions)
  
  chr_name <- mSetsAnno$anno_targets@genome$chr
  chr_size <- mSetsAnno$anno_targets@genome$size
  genome_chr <- cumsum(as.numeric(chr_size))
  chr_centr <- mSetsAnno$anno_targets@genome$pq
  
  #just for getting pq - lines
  addChr <- c(0,genome_chr)
  addChr <- addChr[-length(addChr)]
  genome_centr <- chr_centr + addChr
  
  #defining threshholds
  broad_min_probes <- 300
  focal_min_probes <- 2
  
  #x-axis
  axis_break <- genome_centr
  axis_label <- c(1:22)
  b <- c(-1, -0.5, 0, 0.5, 1)
  
  #segment
  segstart <- seg_mpcf$start.pos
  segend <- seg_mpcf$end.pos
  segnames <- as.numeric(seg_mpcf$chrom)
  
  segment_data <- as.data.frame(cbind(segstart, segend, segnames))
  colnames(segment_data) <- c("seg_start", "seg_end" , "chr")
  
  #calculate position on genome
  seg_start <- c()
  seg_end <- c()
  foreach(i=1:length(segment_data$chr)) %do%
  {
   seg_start[i] <- segment_data$seg_start[i] + addChr[segment_data$chr[i]]
    seg_end[i] <- segment_data$seg_end[i] + addChr[segment_data$chr[i]]
  }
  
  seg_data_samples <- seg_mpcf[,-(which(names(seg_mpcf) %in% c("chrom", "arm", "start.pos", "end.pos", "n.probes")))]
  df_seg_val <- as.data.frame(cbind(seg_start, seg_end,  rowMeans(seg_data_samples)))
  df_abberation_candidates <- as.data.frame(cbind(seg_start, seg_end, seg_mpcf$n.probes, seg_data_samples))
  
  #focal candidates
  focal_candidates <- df_abberation_candidates
  focal_candidates$seg_end <- focal_candidates$seg_end + 10000000
  focal_candidates <- focal_candidates[!((abs(focal_candidates$`seg_mpcf$n.probes`)) < focal_min_probes),]
  focal_candidates$mean <- rowMeans(seg_data_samples)
  focal_candidates$col <- "amplification"
  focal_candid_values <- focal_candidates[,-(1:5)]
  focalcount <- c(1:length(focal_candidates$seg_start))
  for (i in focalcount) {
    focal_candidates$count[i] <- max(0, (sum(focal_candid_values[i,] >= thresh)) )
    if (focal_candidates$mean[i] < 0)
    {
      focal_candidates$count[i] <- focal_candidates$count[i] * -1
      focal_candidates$col[i] <- "deletion"
    }
  }
  
  #broad candidates
  broad_candidates <- df_abberation_candidates
  broad_candidates$mean <- rowMeans(seg_data_samples)
  broad_candidates <- broad_candidates[!((abs(broad_candidates$`seg_mpcf$n.probes`)) < broad_min_probes),]
  broad_candid_values <- abs(broad_candidates[,-(1:5)])
  broadcount <- c(1:length(broad_candid_values$mean))
  broad_candidates$col <- "amplification"
  for (i in broadcount) {
    broad_candidates$count[i] <- max(0, (sum(broad_candid_values[i,] >= thresh)) )
    if (broad_candidates$mean[i] < 0)
    {
      broad_candidates$count[i] <- broad_candidates$count[i] * -1
      broad_candidates$col[i] <- "deletion"
    }
  }
  
  candidates <- rbind(focal_candidates[(focal_candidates$count!=0),], broad_candidates[(broad_candidates$count!=0),])
  sample_no <- ncol(seg_data_samples)
  b <- c(-1, -0.5, 0, 0.5, 1)
  y_axis_break <-c(-sample_no,-(sample_no/2) + -(sample_no/4), -(sample_no/2), -(sample_no/4),0, sample_no/4, sample_no/2,(sample_no/2) + (sample_no/4), sample_no)
  y_axis_label <- c("100","75", "50","25", "0","25", "50","75", "100" )
  
  cumFreq <- ggplot() + 
    geom_rect(data = candidates,  aes(xmin = seg_start, xmax = seg_end, ymax = count, ymin = 0 , fill = col))  +
    geom_vline(xintercept = genome_chr, colour = "grey") +
    geom_vline(xintercept = genome_centr, linetype="dotted", colour = "grey") +
    geom_hline( yintercept = 0, colour ="darkgrey") +
    scale_x_continuous(name = "Chromosome", breaks = axis_break, labels = axis_label, limits = c(0, 2881033286)) +
    theme_classic(base_size = 15) +
    guides(x = guide_axis(angle = 40)) +
    scale_y_continuous(name = "Occurrence over all samples [%]", breaks = y_axis_break, labels = y_axis_label, limits = c(-sample_no, sample_no)) +
    scale_fill_discrete(guide="none") +
    scale_fill_manual(values = c("amplification" = colour.amplification,"deletion" = colour.loss), guide="none") +
    coord_cartesian(xlim = c(50001, 2881033286), expand = FALSE) +
    guides(x = guide_axis(n.dodge = 2))
  
  #draw plots
  print(cumCNV)
  print(cumFreq)

}
```

```{r}
CCNV <- function(mSetsAnno, seg_mpcf, target_ratios, colour.amplification, colour.loss, detail.regions){
  annotate = TRUE
  if(is.null(detail.regions)){
    annotate = FALSE
  }
  
  bin_data_samples <- target_ratios[,-(which(names(target_ratios) %in% c("Chrom", "Median.bp")))]
  bin_data_all <- as.data.frame(cbind(as.numeric(mSetsAnno$anno_targets@bins@ranges@start), as.numeric(rowMeans(bin_data_samples)), target_ratios$Chrom))
  colnames(bin_data_all)<- c("bin_start", "bin_value", "names")

  #genome data
  chr_name <- mSetsAnno$anno_targets@genome$chr
  chr_size <- mSetsAnno$anno_targets@genome$size
  genome_chr <- cumsum(as.numeric(chr_size))
  chr_centr <- mSetsAnno$anno_targets@genome$pq
  
  #just for getting pq - lines
  addChr <- c(0,genome_chr)
  addChr <- addChr[-length(addChr)]
  genome_centr <- chr_centr + addChr
  
  #calculate position on genome
  start = c()
  foreach(i=1:length(bin_data_all$bin_start)) %do%
  {
    start[i] <- bin_data_all$bin_start[i] + addChr[bin_data_all$names[i]]
  }
  
  # bin data consisting out of the starting point of the bin and the value
  final_bin_data <- as.data.frame(cbind(as.numeric(start), bin_data_all$bin_value))
  final_bin_data$bin_nr <- rownames(final_bin_data)
  
  #segment data
  seg_data_samples <- seg_mpcf[,-(which(names(seg_mpcf) %in% c("chrom", "arm", "start.pos", "end.pos", "n.probes")))]
  #mean seg value
  segSta <- as.data.frame(cbind(seg_mpcf$start.pos, rowMeans(seg_data_samples), as.numeric(seg_mpcf$chrom)))
  segEnd <- as.data.frame(cbind(seg_mpcf$end.pos, rowMeans(seg_data_samples), as.numeric(seg_mpcf$chrom)))
  names(segEnd) <- names(segSta)
  segment_data <- as.data.frame(rbind(segSta, segEnd))
  colnames(segment_data) <- c("seg_lim", "seg_val", "chr")
  
  #calculate position on genome
  seg_start = c()
  foreach(i=1:length(segment_data$chr)) %do%
  {
   seg_start[i] <- segment_data$seg_lim[i] + addChr[segment_data$chr[i]]
  }
  
  final_seg_data <- as.data.frame(cbind(as.numeric(seg_start), as.numeric(segment_data$seg_val)))
  final_seg_data <-final_seg_data[order(final_seg_data$V1),]
  
  #x-axis
  axis_break <- genome_centr
  axis_label <- c(1:22)
  b <- c(-1, -0.5, 0, 0.5, 1)
  
  
  if (annotate == TRUE) {
    if (ArrayType != "EPIC"){
      anno <- getAnnotation(IlluminaHumanMethylation450kanno.ilmn12.hg19)
    }
    if (ArrayType == "EPIC"){
      anno <- getAnnotation(IlluminaHumanMethylationEPICanno.ilm10b4.hg19)
    }
    
    #detail data -> here used to be anno _EPIC
    gene_regions <- as.data.frame(cbind(anno@listData$UCSC_RefGene_Name, anno@rownames, anno@listData$chr, anno@listData$pos))
    colnames(gene_regions) <- c("genes", "CpG_sites", "chr", "pos")
    gene_regions$genes <- gsub(";"," ",gene_regions$genes)
    gene_regions$chr <- gsub("chr", "", gene_regions$chr)
    df_gene_regions <- gene_regions[!(gene_regions$chr=="X" | gene_regions$chr=="Y"),]
    df_gene_regions$chr <- as.numeric(df_gene_regions$chr)
    df_gene_regions$pos <- as.numeric(df_gene_regions$pos)
    
    #calculate position on genome
    cpg_pos = c()
    counter3 <- 1:length(df_gene_regions$chr)
    for(i in counter3){
      cpg_pos[i] <- df_gene_regions$pos[i] + addChr[df_gene_regions$chr[i]]
    }
    df_gene_regions$pos <- as.numeric(cpg_pos)
    genes <- as.data.frame(detail_regions$name)
    
    
    final_bin_data <-  na.omit(final_bin_data)
    df_gene_regions$bin <- final_bin_data$bin_nr[findInterval(df_gene_regions$pos, final_bin_data$V1)]
    df_gene_regions <- as.data.frame(na.omit(as.matrix(df_gene_regions)))
    df_gene_regions <- separate(df_gene_regions, genes, into = c("genes1", "genes2"), sep = " (?=[^ ]+$)")
    
    #put together the genes and the corresponding bin data
    geneBins <- left_join(genes, df_gene_regions ,join_by("detail_regions$name" == "genes1"))
    
    #remove duplicates and only keep the bin with the highest number of CpG sites present
    geneBins <- geneBins %>% group_by(geneBins$`detail_regions$name`) %>% dplyr::count(geneBins$`detail_regions$name`, geneBins$bin)
    colnames(geneBins) <- c("genes", "bins", "n")
    geneBins <- geneBins[order(geneBins$n, decreasing  = TRUE),]
    geneBins <- na.omit(geneBins[-which(duplicated(geneBins$genes)),])
    
    geneBins <- left_join(geneBins, final_bin_data, join_by("bins" == "bin_nr"))
    geneBins <- geneBins[!((abs(geneBins$V2)) <0.15),]
  
    cumCNV <- ggplot() +
    geom_point(final_bin_data, mapping = aes(x=V1, y=V2, colour=V2))+ 
    ylim(-2, 2) + 
    scale_color_gradient2(low = colour.loss ,  mid = "white",  high = colour.amplification,  midpoint = 0, breaks = b, guide = "colourbar" , space = "Lab", name = "Intensity") + 
    geom_vline(xintercept = genome_chr, colour = "grey") + 
    geom_vline(xintercept = genome_centr,linetype="dotted", colour = "grey")  + 
    geom_path(data = final_seg_data, aes(x = V1, y = V2)) + 
    labs( y = "Intensity") + 
    geom_point(data = geneBins, aes(x = geneBins$V1, y = geneBins$V2)) + 
    geom_label_repel(data = geneBins, aes(x = geneBins$V1, y = geneBins$V2), label = geneBins$genes, label.size = 0.2, nudge_x = 0.1, nudge_y = 0.1,) + 
    scale_x_continuous(limits = c(10001, 2881033286), name = "Chromosome", breaks = axis_break, labels = axis_label ) +
    theme_classic(base_size = 15) + 
    coord_cartesian(xlim = c(50001, 2881033286), expand = FALSE) + 
    guides(x = guide_axis(n.dodge = 2))
  }
  
  if (annotate == FALSE){
    cumCNV <- ggplot() +
    geom_point(final_bin_data, mapping = aes(x=V1, y=V2, colour=V2))+ 
    ylim(-2, 2) + 
    scale_color_gradient2(low = colour.loss ,  mid = "white",  high = colour.amplification,  midpoint = 0, breaks = b, guide = "colourbar" , space = "Lab", name = "Intensity") + 
    geom_vline(xintercept = genome_chr, colour = "grey") + 
    geom_vline(xintercept = genome_centr,linetype="dotted", colour = "grey")  + 
    geom_path(data = final_seg_data, aes(x = V1, y = V2)) + 
    labs(y = "Intensity") +
    scale_x_continuous(limits = c(10001, 2881033286), name = "Chromosome", breaks = axis_break, labels = axis_label ) +
    theme_classic(base_size = 15) + 
    coord_cartesian(xlim = c(50001, 2881033286), expand = FALSE) + 
    guides(x = guide_axis(n.dodge = 2))
  }
  return(cumCNV)
}
```



```{r read and segment data}
singleSampleSeg<- function(mSetsAnno, ArrayType, thresh, colour.amplification, colour.loss){
  
  start.time <- Sys.time()
  #load and bin each sample in conumee
  foreach(i=1:ncol(mSetsAnno$target_mset_loaded@intensity)) %do%
  {
    if (i == 1) {
      x <- CNV.segment(CNV.bin(CNV.fit(query = mSetsAnno$target_mset_loaded[names(mSetsAnno$target_mset_loaded[i])], ref = mSetsAnno$control_mset_loaded, mSetsAnno$anno_targets)))
      segmentation_data <- as.data.frame(cbind(x@seg$summary$chrom, x@seg$summary$loc.start, x@seg$summary$loc.end, x@seg$summary$seg.mean, names(mSetsAnno$target_mset_loaded[i])))
    }
    else {
      x <- CNV.segment(CNV.bin(CNV.fit(query = mSetsAnno$target_mset_loaded[names(mSetsAnno$target_mset_loaded[i])], ref = mSetsAnno$control_mset_loaded, mSetsAnno$anno_targets)))
      target_segmentation <- as.data.frame(cbind(x@seg$summary$chrom, x@seg$summary$loc.start, x@seg$summary$loc.end, x@seg$summary$seg.mean, names(mSetsAnno$target_mset_loaded[i])))
      names(target_segmentation) <- names(segmentation_data)
      segmentation_data <- rbind(segmentation_data, target_segmentation)
    }
  }
  end.time <- Sys.time()
 time.taken <- end.time - start.time
 print(time.taken)
  names(segmentation_data) <- c("chromosome", "start", "end","segmean", "sample")
  
  segmentation_data$chromosome <- gsub("chr","",segmentation_data$chromosome)
  segmentation_data$chromosome <- as.numeric(segmentation_data$chromosome)
  sample_no <- as.numeric(length(unique(segmentation_data$sample)))
  segmentation_data$start <- as.numeric(segmentation_data$start)
  segmentation_data$end <- as.numeric(segmentation_data$end)
  segmentation_data$segmean <- as.numeric(segmentation_data$segmean)
  segmentation_data2 <- as.data.frame(segmentation_data)
  
  #genome data
  chr_name <- mSetsAnno$anno_targets@genome$chr
  chr_size <- mSetsAnno$anno_targets@genome$size
  genome_chr <- cumsum(as.numeric(chr_size))
  chr_centr <- mSetsAnno$anno_targets@genome$pq
  
  #just for getting pq - lines
  addChr <- c(0,genome_chr)
  addChr <- addChr[-length(addChr)]
  genome_centr <- chr_centr + addChr
  
  #calculate position on genome
  seg_start <- c()
  seg_end <- c()
  foreach(i=1:length(segmentation_data$chromosome)) %do%
  {
   seg_start[i] <- segmentation_data$start[i] + addChr[segmentation_data$chromosome[i]]
    seg_end[i] <- segmentation_data$end[i] + addChr[segmentation_data$chromosome[i]] + 10000000
  }
  
  segmentation_data$start <- seg_start
  segmentation_data$end <- seg_end
  

  axis_break <- genome_centr
  axis_label <- c(1:22)
  
  segcount <- c(1:length(segmentation_data$segmean))
  segmentation_data$col <- "amplification"
  for (i in segcount) {
    if (segmentation_data$segmean[i] < 0)
    {
      segmentation_data$col[i] <- "deletion"
    }
  }
  
  overlayPlot <- ggplot() + 
    geom_rect(data = segmentation_data,  aes(xmin = start, xmax = end, ymax = segmean, ymin = 0 , fill = col))  +
    geom_vline(xintercept = genome_chr, colour = "grey") +
    ylim(-2, 2) + 
    geom_vline(xintercept = genome_centr, linetype="dotted", colour = "grey") +
    geom_hline( yintercept = 0, colour ="darkgrey") +
    scale_x_continuous(name = "Chromosome", breaks = axis_break, labels = axis_label, limits = c(0, 2881033286)) +
    theme_classic(base_size = 15) +
    guides(x = guide_axis(angle = 40)) +
    scale_fill_discrete(guide="none") +
    coord_cartesian(xlim = c(50001, 2881033286), expand = FALSE) +
    guides(x = guide_axis(n.dodge = 2))+
    scale_fill_manual(values = alpha(c("amplification" = colour.amplification,"deletion" = colour.loss), 1/sample_no), guide="none")

  cnFreq_seg <- as.data.frame(cnFreq(segmentation_data2, CN_low_cutoff = -thresh,  CN_high_cutoff = thresh, out = "data"))
  cnFreq_seg$data.chromosome <- gsub("chr", "", cnFreq_seg$data.chromosome)
  cnFreq_seg$data.chromosome <- as.numeric(cnFreq_seg$data.chromosome)
  
  data.start = c()
  data.end = c()
  counterCnFreq <- 1:length(cnFreq_seg$data.chromosome)
  for(i in counterCnFreq){
    data.start[i] <- cnFreq_seg$data.start[i] + addChr[cnFreq_seg$data.chromosome[i]]
    data.end[i] <- cnFreq_seg$data.end[i] + addChr[cnFreq_seg$data.chromosome[i]]
  }
  
  cnFreq_seg$data.start <- as.numeric(data.start)
  cnFreq_seg$data.end <- as.numeric(data.end)
  cnFreq_seg$data.lossProportion <- cnFreq_seg$data.lossProportion*-1
  
  #duplicate rows/segment with gains and loss
  df.expanded <- cnFreq_seg[rep(row.names(cnFreq_seg), ifelse(cnFreq_seg$data.gainProportion != 0 & cnFreq_seg$data.lossProportion != 0 ,2 ,1)),]
  
  #now every row is one rectangle of the final plot, extra rows have .1 in their name
  df.expanded$new_rownames <- rownames(df.expanded)
  
  #define the heights of these rectangles
  df.expanded$Y_MIN <- ifelse(df.expanded$data.gainProportion == 0 | df.expanded$data.lossProportion == 0, df.expanded$data.lossProportion, ifelse(grepl("\\.1", df.expanded$new_rownames), df.expanded$data.lossProportion, 0))
  
  df.expanded$Y_MAX <- ifelse(df.expanded$data.gainProportion == 0 | df.expanded$data.lossProportion == 0, df.expanded$data.gainProportion, ifelse(grepl("\\.1", df.expanded$new_rownames), 0, df.expanded$data.gainProportion))
  
  #decribe segment properties
  df.expanded$type <- ifelse(df.expanded$data.gainProportion == 0 & df.expanded$data.lossProportion == 0, "neutral", ifelse(df.expanded$Y_MAX == 0, "loss", "gain"))
   
  #separate into two dataframes for filtering
  gains <- df.expanded[which(df.expanded$type == "gain"),]
  loss <- df.expanded[which(df.expanded$type == "loss"),]
  
  gains_filtered_for_plot <- as.data.frame(cbind(gains$data.start, gains$data.end, gains$data.gainProportion, gains$type))
  loss_filtered_for_plot <- as.data.frame(cbind(loss$data.start, loss$data.end, loss$data.lossProportion, loss$type))
  
  #names(gains_filtered_for_plot) <- c("start", "end", "count", "type")
  names(loss_filtered_for_plot) <- names(gains_filtered_for_plot)
  
  to_plot <- as.data.frame(rbind(gains_filtered_for_plot, loss_filtered_for_plot ))
  names(to_plot) <- c("start", "end", "count", "type")
  
  b <- c(-1, -0.5, 0, 0.5, 1)
  y_axis_break <-c(-sample_no,-(sample_no/2) + -(sample_no/4), -(sample_no/2), -(sample_no/4),0, sample_no/4, sample_no/2,(sample_no/2) + (sample_no/4), sample_no)
  y_axis_label <- c("100","75", "50","25", "0","25", "50","75", "100" )
  
  to_plot$start <- as.numeric(to_plot$start)
  to_plot$end <- as.numeric(to_plot$end)
  to_plot$end <- to_plot$end + 5000000
  to_plot$count <- as.numeric(to_plot$count)
  
  singleFreqPlot <- ggplot() + geom_rect(data = to_plot,  aes(xmin = start, xmax = end, ymax = count, ymin = 0 , fill = type))  +
    geom_vline(xintercept = genome_chr, colour = "grey") + 
    geom_vline(xintercept = genome_centr, linetype="dotted", colour = "grey") + 
    geom_hline(yintercept = 0, colour ="darkgrey") + 
    scale_x_continuous(name = "Chromosome", breaks = axis_break, labels = axis_label, limits = c(0, 2881033286)) +
    theme_classic(base_size = 12) + 
    guides(x = guide_axis(angle = 40)) +
    scale_y_continuous(name = "Intensity", breaks = y_axis_break, labels = y_axis_label, limits = c(-sample_no, sample_no))+
    scale_fill_discrete(guide="none") + 
    scale_fill_manual(values = c("gain" = colour.amplification,"loss" = colour.loss), guide="none") + 
    coord_cartesian(xlim = c(50001, 2881033286), expand = FALSE) + 
    guides(x = guide_axis(n.dodge = 2))

  #draw plots
  print(overlayPlot)
  print(singleFreqPlot)
}
```

```{r}
cum.CNV <- function(datafile, ArrayType = "overlap", segmentationMode = "all", thresh = 0.2, colour.amplification = "red3", colour.loss = "blue4", detail.regions = NULL){
  
  #read data transform to RGChannelSet
  if (ArrayType == "overlap") {
    data_EPIC <- target_files[which(target_files$ArrayType == "EPIC"),]
    data_450k <- target_files[which(target_files$ArrayType == "450k"),]

    # separately prepare 450k and 850k and then combine them
    rgset_EPIC <- read.metharray.exp(targets = data_EPIC, force = TRUE)
    rgset_450k <- read.metharray.exp(targets = data_450k, force = TRUE)

    target_rgset <- combineArrays(rgset_EPIC, rgset_450k, outType = "IlluminaHumanMethylation450k")
  }
  if (ArrayType == "450k") {
    rgset_450k <- read.metharray.exp(targets = target_files, force = TRUE)
  
    target_rgset <- rgset_450k
  
  }
  if (ArrayType == "EPIC") {
    rgset_EPIC <- read.metharray.exp(targets = target_files, force = TRUE)
  
    target_rgset <- rgset_EPIC
  }   
  if (segmentationMode == "single") {
    mSetsAnno <-  sampleBinContr(target_rgset, ArrayType)
    singleSampleSeg(mSetsAnno, ArrayType, thresh, colour.amplification, colour.loss)
  } 
  if (segmentationMode == "multi") {
    mSetsAnno <-  sampleBinContr(target_rgset, ArrayType)
    multiSampleSeg(mSetsAnno, ArrayType, thresh, colour.amplification, colour.loss, detail.regions)
  } 
  if (segmentationMode == "all") {
    mSetsAnno <-  sampleBinContr(target_rgset, ArrayType)
    multiSampleSeg(mSetsAnno, ArrayType, thresh, colour.amplification, colour.loss, detail.regions)
    singleSampleSeg(mSetsAnno, ArrayType, thresh, colour.amplification, colour.loss)
  } 
  
}

p <- cum.CNV(target_files, ArrayType = "EPIC", segmentationMode = "multi")
```




